import 'package:ricochet_robots/models/goal.dart';
import 'package:ricochet_robots/models/grid.dart';
import 'package:ricochet_robots/models/robot.dart';

class BoardBuilder {
  // TODO: change patterns randomly.
  static List<List<Grid>> buildGrids() {
    return [
      [
        NormalGrid(canMoveUp: false, canMoveLeft: false),
        NormalGrid(canMoveUp: false, canMoveRight: false),
        NormalGrid(canMoveUp: false, canMoveLeft: false),
        NormalGrid(canMoveUp: false),
        NormalGrid(canMoveUp: false, canMoveDown: false),
        NormalGrid(canMoveUp: false),
        NormalGrid(canMoveUp: false),
        NormalGrid(canMoveUp: false),
        NormalGrid(canMoveUp: false),
        NormalGrid(canMoveUp: false),
        NormalGrid(canMoveUp: false),
        NormalGrid(canMoveUp: false, canMoveRight: false),
        NormalGrid(canMoveUp: false, canMoveLeft: false),
        NormalGrid(canMoveUp: false, canMoveDown: false),
        NormalGrid(canMoveUp: false),
        NormalGrid(canMoveUp: false, canMoveRight: false),
      ],
      [
        NormalGrid(canMoveLeft: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
        NormalGoalGrid(
          color: RobotColors.red,
          type: GoalTypes.moon,
          canMoveUp: false,
          canMoveLeft: false,
        ),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
        NormalGoalGrid(
          color: RobotColors.red,
          type: GoalTypes.planet,
          canMoveUp: false,
          canMoveLeft: false,
        ),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
      ],
      [
        NormalGrid(canMoveLeft: false),
        NormalGoalGrid(
          color: RobotColors.green,
          type: GoalTypes.sun,
          canMoveUp: false,
          canMoveRight: false,
        ),
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGoalGrid(
          color: RobotColors.blue,
          type: GoalTypes.sun,
          canMoveRight: false,
          canMoveDown: false,
        ),
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
      ],
      [
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGoalGrid(
          color: RobotColors.yellow,
          type: GoalTypes.star,
          canMoveRight: false,
          canMoveDown: false,
        ),
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(canMoveUp: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveRight: false, canMoveDown: false),
      ],
      [
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveUp: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveUp: false, canMoveRight: false),
      ],
      [
        NormalGrid(canMoveLeft: false, canMoveDown: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveDown: false),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
        NormalGoalGrid(
          color: RobotColors.green,
          type: GoalTypes.star,
          canMoveDown: false,
          canMoveLeft: false,
        ),
        NormalGrid(canMoveRight: false),
      ],
      [
        NormalGrid(canMoveLeft: false, canMoveUp: false),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
        NormalGoalGrid(
          color: RobotColors.blue,
          type: GoalTypes.planet,
          canMoveDown: false,
          canMoveLeft: false,
        ),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(),
        NormalGrid(),
        NormalGoalGrid(
          color: RobotColors.yellow,
          type: GoalTypes.moon,
          canMoveUp: false,
          canMoveRight: false,
        ),
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(canMoveUp: false),
        NormalGrid(canMoveRight: false),
      ],
      [
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveUp: false),
        NormalGrid(),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveRight: false),
        CenterGrid(),
        CenterGrid(),
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
      ],
      [
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        WildGoalGrid(canMoveUp: false, canMoveRight: false),
        NormalGrid(canMoveRight: false, canMoveLeft: false),
        CenterGrid(),
        CenterGrid(),
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
      ],
      [
        NormalGrid(canMoveLeft: false),
        NormalGoalGrid(
          color: RobotColors.blue,
          type: GoalTypes.moon,
          canMoveRight: false,
          canMoveDown: false,
        ),
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveUp: false),
        NormalGrid(canMoveUp: false, canMoveDown: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGoalGrid(
          color: RobotColors.yellow,
          type: GoalTypes.planet,
          canMoveRight: false,
          canMoveDown: false,
        ),
        NormalGrid(canMoveRight: false, canMoveLeft: false),
      ],
      [
        NormalGrid(canMoveLeft: false),
        NormalGrid(canMoveUp: false),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
        NormalGoalGrid(
          color: RobotColors.green,
          type: GoalTypes.planet,
          canMoveDown: false,
          canMoveLeft: false,
        ),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGoalGrid(
          color: RobotColors.red,
          type: GoalTypes.sun,
          canMoveUp: false,
          canMoveRight: false,
        ),
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveUp: false),
        NormalGrid(canMoveRight: false, canMoveDown: false),
      ],
      [
        NormalGrid(canMoveDown: false, canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveUp: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
        NormalGoalGrid(
          color: RobotColors.green,
          type: GoalTypes.moon,
          canMoveDown: false,
          canMoveLeft: false,
        ),
        NormalGrid(),
        NormalGrid(canMoveUp: false, canMoveRight: false),
      ],
      [
        NormalGrid(canMoveUp: false, canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveDown: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveDown: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveUp: false),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
      ],
      [
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveDown: false),
        NormalGrid(),
        NormalGoalGrid(
          color: RobotColors.red,
          type: GoalTypes.star,
          canMoveUp: false,
          canMoveRight: false,
        ),
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
        NormalGoalGrid(
          color: RobotColors.blue,
          type: GoalTypes.star,
          canMoveUp: false,
          canMoveLeft: false,
        ),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
      ],
      [
        NormalGrid(canMoveLeft: false),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
        NormalGoalGrid(
          color: RobotColors.yellow,
          type: GoalTypes.sun,
          canMoveUp: false,
          canMoveLeft: false,
        ),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(),
        NormalGrid(canMoveRight: false),
      ],
      [
        NormalGrid(canMoveDown: false, canMoveLeft: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveRight: false, canMoveDown: false),
        NormalGrid(canMoveDown: false, canMoveLeft: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveRight: false, canMoveDown: false),
        NormalGrid(canMoveDown: false, canMoveLeft: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveDown: false),
        NormalGrid(canMoveRight: false, canMoveDown: false),
      ],
    ];
  }
}
